name: build workflow

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs: 
  linux:
    uses: ./.github/workflows/linux.yml

  macos:
    uses: ./.github/workflows/mac.yml

  windows:
    uses: ./.github/workflows/windows.yml