name: Build application for linux

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
            
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: install wasm
        run: rustup target add wasm32-unknown-unknown

      - name: install tauri
        run: |
          if ! command -v tauri &> /dev/null; then
            cargo install tauri-cli
          fi

      - name: install trunk
        run: |
          if ! command -v trunk &> /dev/null; then
            cargo install --locked trunk
          fi
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libglib2.0-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config \
            build-essential
            
      - name: building application
        run: cargo tauri build
            
      - name: rename installer
        run: mv ./target/release/bundle/appimage/activity-manager_0.1.0_amd64.AppImage ./target/release/bundle/appimage/activity-manager-${{github.ref_name}}.AppImage
            
      - name: Create GitHub Release  
        uses: softprops/action-gh-release@v2  
        with:  
          files: ./target/release/bundle/appimage/activity-manager-${{github.ref_name}}.AppImage
          tag_name: ${{ github.ref_name }}
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}