name: Build application

on:
    workflow_call:

permissions:
  contents: write

jobs:
    build:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
            uses: actions/checkout@v4
            with: 
            fetch-depth: 0
        
        - name: setup rust
            uses: actions-rust-lang/setup-rust-toolchain@v1

        - name: install tauri
            run: cargo install tauri-cli
        
        - name: building application
            run: cargo tauri build
        
        - name: rename installer
            run: mv ./target/macos/activity-manager_0.1.0_amd64.deb ./target/macos/activity-manager-${{github.ref_name}}.AppImage
        
        - name: Create GitHub Release  
            uses: softprops/action-gh-release@v2  
            with:  
                files:
                    - ./target/macos/activity-manager-${{github.ref_name}}.AppImage
                tag_name: ${{ github.ref_name }}
            env:  
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}