name: Build application for windows

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
            
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\.cargo\bin
            C:\Users\runneradmin\.cargo\registry
            C:\Users\runneradmin\.cargo\git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: install wasm
        run: rustup target add wasm32-unknown-unknown

      - name: install tauri
        run: |
          if (-not (Get-Command tauri -ErrorAction SilentlyContinue)) {
              cargo install tauri-cli
          }

      - name: install trunk
        run: |
          if (-not (Get-Command trunk -ErrorAction SilentlyContinue)) {
            cargo install --locked trunk
          }
            
      - name: building application
        run: cargo tauri build
            
      - name: rename installer
        run: |
          if (Test-Path "target/release/bundle/nsis/activity-manager-${{github.ref_name}}-installer.exe") { Remove-Item "target/release/bundle/nsis/activity-manager-${{github.ref_name}}-installer.exe" }
          Rename-Item -Path "target/release/bundle/nsis/activity-manager_0.1.0_x64-setup.exe" -NewName "activity-manager-${{github.ref_name}}-installer.exe" -Force
            
      - name: Create GitHub Release  
        uses: softprops/action-gh-release@v2  
        with:  
          files: target/release/bundle/nsis/activity-manager-${{github.ref_name}}-installer.exe
          tag_name: ${{ github.ref_name }}
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}